export default {
  id: '3701828',
  name: '猎运PC',
  font_family: 'iconfont',
  css_prefix_text: 'kx-',
  description: '',
  glyphs: [
    {
      icon_id: '32265492',
      name: '客户类型',
      font_class: 'kehuleixing',
      unicode: 'e6c8',
      unicode_decimal: 59080,
    },
    {
      icon_id: '32265493',
      name: '客户列表',
      font_class: 'kehuliebiao',
      unicode: 'e6c9',
      unicode_decimal: 59081,
    },
    {
      icon_id: '32265494',
      name: '体验客户',
      font_class: 'tiyankehu',
      unicode: 'e6ca',
      unicode_decimal: 59082,
    },
    {
      icon_id: '32265495',
      name: '司机列表',
      font_class: 'sijiliebiao',
      unicode: 'e6cb',
      unicode_decimal: 59083,
    },
    {
      icon_id: '32265496',
      name: '车辆字段',
      font_class: 'cheliangziduan',
      unicode: 'e6cc',
      unicode_decimal: 59084,
    },
    {
      icon_id: '32265497',
      name: '车辆列表',
      font_class: 'cheliangliebiao',
      unicode: 'e6cd',
      unicode_decimal: 59085,
    },
    {
      icon_id: '32265498',
      name: '发货路线',
      font_class: 'fahuoluxian',
      unicode: 'e6ce',
      unicode_decimal: 59086,
    },
    {
      icon_id: '32265499',
      name: '地址信息',
      font_class: 'dizhixinxi',
      unicode: 'e6cf',
      unicode_decimal: 59087,
    },
    {
      icon_id: '32265504',
      name: '角色管理',
      font_class: 'jiaoseguanli',
      unicode: 'e6d0',
      unicode_decimal: 59088,
    },
    {
      icon_id: '32265505',
      name: '部门管理',
      font_class: 'bumenguanli',
      unicode: 'e6d1',
      unicode_decimal: 59089,
    },
    {
      icon_id: '32265506',
      name: '菜单管理',
      font_class: 'caidanguanli',
      unicode: 'e6d2',
      unicode_decimal: 59090,
    },
    {
      icon_id: '32265507',
      name: '用户管理',
      font_class: 'yonghuguanli',
      unicode: 'e6d3',
      unicode_decimal: 59091,
    },
    {
      icon_id: '32265291',
      name: '首页',
      font_class: 'shouye',
      unicode: 'e6c7',
      unicode_decimal: 59079,
    },
  ],
};
